name: Continuous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch  
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "main" ] # Corrected from 'branch' to 'branches'

  push:
    branches: [ "main" ] # Corrected from 'branch' to 'branches'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Avoid redundant parallel runs on the same PR
# Root Level Concurrency block
concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Skip build execution on draft PRs to conserve minutes
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Environment & Workspace
        run: |
          echo "Building commit: ${{ github.sha }}"
          java -version
          mvn -version
          ls -ltrga

      - name: Build and Test with Maven
        run: mvn verify -T 1C -B

      - name: Upload Test Results
        if: always() # Ensure this step runs even if the previous step fails
        uses: actions/upload-artifact@v4 # V3 is deprecated and hence github action failed
        with:
          name: test-reports
          path: |
            target/surefire-reports # standard Maven test report location
            target/failsafe-reports # standard Maven test report location
          if-no-files-found: ignore # Please ignore if no files found ## we will check this later
